name: Release system_profiler

on:
  push:
    tags:
      - 'latest'
    paths:
      - 'system_profiler/**'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          cd system_profiler
          make deps
          make build

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: system_profiler-binaries
          path: |
            system_profiler/system_profiler-x86_64.ext
            system_profiler/system_profiler-arm64.ext
            system_profiler/system_profiler.ext

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Fleet Extensions Release
          body: |
            # Fleet Extensions Release

            This release includes updated binaries for the following extensions:

            | Extension              | Built in this release |
            |------------------------|----------------------|
            | macos_compatibility    |                      |
            | santa                  |                      |
            | system_profiler        | ✅                   |
            | snap_packages          |                      |
            | nuget_packages         |                      |

            See attached assets for binaries.
          files: |
            system_profiler/system_profiler-x86_64.ext
            system_profiler/system_profiler-arm64.ext
            system_profiler/system_profiler.ext
          draft: false
          prerelease: false 