name: Release brew_list

on:
  push:
    tags:
      - 'latest'
    paths:
      - 'brew_list/**'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          cd brew_list
          make deps
          make build

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: brew_list-binaries
          path: |
            brew_list/brew_list.ext

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Fleet Extensions Release
          body: |
            This release includes updated binaries for the following extensions:

            | Extension              | Built in this release |
            |------------------------|----------------------|
            | macos_compatibility    |                      |
            | santa                  |                      |
            | system_profiler        |                      |
            | snap_packages          |                      |
            | nuget_packages         |                      |
            | brew_list              | ✅                   |

            See attached assets for binaries.
          files: |
            brew_list/brew_list.ext
          draft: false
          prerelease: false

