name: Release nuget_packages

on:
  push:
    tags:
      - 'latest'
    paths:
      - 'nuget_packages/**'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build macOS binaries
        run: |
          cd nuget_packages
          make deps
          make macos

      - name: Upload macOS binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget_packages-macos-binaries
          path: |
            nuget_packages/nuget_packages-x86_64.ext
            nuget_packages/nuget_packages-arm64.ext
            nuget_packages/nuget_packages.ext

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Windows binaries
        run: |
          cd nuget_packages
          go mod tidy
          make windows

      - name: Upload Windows binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget_packages-windows-binaries
          path: |
            nuget_packages/nuget_packages-amd64.exe
            nuget_packages/nuget_packages-arm64.exe

  release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Fleet Extensions Release
          body: |
            # Fleet Extensions Release

            This release includes updated binaries for the following extensions:

            | Extension              | Built in this release |
            |------------------------|----------------------|
            | macos_compatibility    |                      |
            | santa                  |                      |
            | system_profiler        |                      |
            | snap_packages          |                      |
            | nuget_packages         | ✅                   |

            See attached assets for binaries.
          files: |
            ./artifacts/**/nuget_packages-x86_64.ext
            ./artifacts/**/nuget_packages-arm64.ext
            ./artifacts/**/nuget_packages.ext
            ./artifacts/**/nuget_packages-amd64.exe
            ./artifacts/**/nuget_packages-arm64.exe
          draft: false
          prerelease: false 