name: Release macos_compatibility

on:
  push:
    tags:
      - 'latest'
    paths:
      - 'macos_compatibility/**'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          cd macos_compatibility
          make deps
          make build

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos_compatibility-binaries
          path: |
            macos_compatibility/macos_compatibility-x86_64.ext
            macos_compatibility/macos_compatibility-arm64.ext
            macos_compatibility/macos_compatibility.ext

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Fleet Extensions Release
          body: |
            This release includes updated binaries for the following extensions:

            | Extension              | Built in this release |
            |------------------------|----------------------|
            | macos_compatibility    | ✅                   |
            | santa                  |                      |
            | system_profiler        |                      |
            | snap_packages          |                      |
            | nuget_packages         |                      |

            See attached assets for binaries.
          files: |
            macos_compatibility/macos_compatibility-x86_64.ext
            macos_compatibility/macos_compatibility-arm64.ext
            macos_compatibility/macos_compatibility.ext
          draft: false
          prerelease: false 